# Generated by Django 3.1.1 on 2020-09-04 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_api', '0004_auto_20200904_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_pass', message='Password must contain at least one uppercase and lowercase character and at least 8 characters.', regex='^(?=.*[a-z])(?=.*[A-Z])[a-zA-Z\\d]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone no. has to be exactly 10 characters', regex='^.{10}$')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='invalid_pincode', message='Pincode has to be exactly 6 characters', regex='^.{6}$')]),
        ),
    ]
